### PR TITLE
Draft: Add support for Vision

### PR DESCRIPTION
**Pull request by slashequip**
Adds support for Vision to [OpenAI](https://platform.openai.com/docs/guides/vision) and [Anthropic](https://docs.anthropic.com/en/docs/build-with-claude/vision).

### CODE REVIEW

**Comment by slashequip** [comment]
@sixlive what do you think of this approach?

**Comment by slashequip** [comment]
Would resolve #32

**Comment by sixlive** [comment]
I think this is a solid start, I'll sleep on it and might pick this up tomorrow. This is definitely high on my list of things I want to enable.

**Comment by slashequip** [comment]
I've actually rolled almost exactly this logic out in a custom OpenAI provider from my app internally and it works great.

**Comment by sixlive** [comment]
image

I've got it it working with Prism Server for OpenAI but it will need some work for Anthropic. This isn't too far off how I was going to approach things. I'm going to run with this a bit. Its going to be my focus going into next week.

**Comment by sixlive** [comment]
Closing in favor of https://github.com/echolabsdev/prism/pull/42

**Pull request closed without merging**
